version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "npm"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      actions:
        patterns:
          - "*"
