/**
 * ZenoDeck Subtitle & Caption Engine (src/lib/youtube/subtitles.ts)
 * =================================================================
 * Fetches, parses, and converts YouTube timedtext transcripts into standard
 * SubRip (.srt), WebVTT (.vtt), and clean plain text (.txt).
 * 100% Client-Side & Offline Ready.
 */

import { universalFetch } from "./innertube";

export interface YouTubeSubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  baseUrl: string;
  vssId?: string;
}

export interface SubtitleCue {
  index: number;
  startMs: number;
  endMs: number;
  text: string;
}

/**
 * Format milliseconds into standard SubRip timestamp: HH:MM:SS,mmm
 */
export function formatSrtTimestamp(ms: number): string {
  const safeMs = Math.max(0, Math.floor(ms));
  const totalSeconds = Math.floor(safeMs / 1000);
  const remainderMs = safeMs % 1000;
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")},${String(remainderMs).padStart(3, "0")}`;
}

/**
 * Format milliseconds into standard WebVTT timestamp: HH:MM:SS.mmm
 */
export function formatVttTimestamp(ms: number): string {
  const safeMs = Math.max(0, Math.floor(ms));
  const totalSeconds = Math.floor(safeMs / 1000);
  const remainderMs = safeMs % 1000;
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}.${String(remainderMs).padStart(3, "0")}`;
}

/**
 * Decode common HTML entities found in subtitle streams
 */
export function decodeHtmlEntities(str: string): string {
  if (!str) return "";
  return str
    .replace(/<[^>]+>/g, "") // strip any residual XML/HTML tags first
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)));
}

/**
 * Parse YouTube json3 timedtext format into normalized cues
 */
export function parseJson3Cues(data: any): SubtitleCue[] {
  const cues: SubtitleCue[] = [];
  if (!data || !Array.isArray(data.events)) return cues;

  let index = 1;
  for (const event of data.events) {
    if (!event.segs || !Array.isArray(event.segs)) continue;

    const startMs = Number(event.tStartMs) || 0;
    const durationMs = Number(event.dDurationMs) || 2000;
    const endMs = startMs + durationMs;

    const text = event.segs
      .map((s: any) => s.utf8 || "")
      .join("")
      .trim();

    if (text && text !== "\n") {
      cues.push({
        index: index++,
        startMs,
        endMs,
        text: decodeHtmlEntities(text),
      });
    }
  }

  return cues;
}

/**
 * Parse legacy YouTube XML transcript into normalized cues
 */
export function parseXmlCues(xmlText: string): SubtitleCue[] {
  const cues: SubtitleCue[] = [];
  if (!xmlText) return cues;

  const regex = /<text\s+start="([0-9.]+)"\s+dur="([0-9.]+)"[^>]*>([\s\S]*?)<\/text>/gi;
  let match: RegExpExecArray | null;
  let index = 1;

  while ((match = regex.exec(xmlText)) !== null) {
    const startSec = parseFloat(match[1]) || 0;
    const durSec = parseFloat(match[2]) || 2;
    const rawText = match[3] || "";

    const text = decodeHtmlEntities(rawText.trim());
    if (text) {
      cues.push({
        index: index++,
        startMs: Math.round(startSec * 1000),
        endMs: Math.round((startSec + durSec) * 1000),
        text,
      });
    }
  }

  return cues;
}

/**
 * Convert cues to SubRip (.srt) string
 */
export function cuesToSrt(cues: SubtitleCue[]): string {
  return cues
    .map(
      (c) =>
        `${c.index}\n${formatSrtTimestamp(c.startMs)} --> ${formatSrtTimestamp(c.endMs)}\n${c.text}\n`
    )
    .join("\n");
}

/**
 * Convert cues to WebVTT (.vtt) string
 */
export function cuesToVtt(cues: SubtitleCue[]): string {
  const body = cues
    .map(
      (c) =>
        `${c.index}\n${formatVttTimestamp(c.startMs)} --> ${formatVttTimestamp(c.endMs)}\n${c.text}\n`
    )
    .join("\n");
  return `WEBVTT\n\n${body}`;
}

/**
 * Convert cues to clean plain text transcript (.txt)
 */
export function cuesToTxt(cues: SubtitleCue[]): string {
  return cues.map((c) => c.text).join("\n");
}

/**
 * Fetch and convert subtitles into the specified format
 */
export async function fetchAndFormatSubtitles(
  track: YouTubeSubtitleTrack,
  format: "srt" | "vtt" | "txt" = "srt"
): Promise<{ content: string; filename: string; mimeType: string }> {
  let targetUrl = track.baseUrl;

  // Prefer json3 format if available
  if (!targetUrl.includes("fmt=")) {
    targetUrl += "&fmt=json3";
  }

  const res = await universalFetch(targetUrl, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    },
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch subtitles: HTTP ${res.status}`);
  }

  const rawText = await res.text();
  let cues: SubtitleCue[] = [];

  try {
    const json = JSON.parse(rawText);
    cues = parseJson3Cues(json);
  } catch {
    // If not json3, parse as XML
    cues = parseXmlCues(rawText);
  }

  if (cues.length === 0) {
    throw new Error("No caption lines found in subtitle track.");
  }

  const ext = format === "srt" ? "srt" : format === "vtt" ? "vtt" : "txt";
  const mimeType =
    format === "srt"
      ? "application/x-subrip"
      : format === "vtt"
      ? "text/vtt"
      : "text/plain";

  const content =
    format === "srt"
      ? cuesToSrt(cues)
      : format === "vtt"
      ? cuesToVtt(cues)
      : cuesToTxt(cues);

  const cleanLang = (track.languageCode || "subtitles").replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = `${cleanLang}_subtitles.${ext}`;

  return { content, filename, mimeType };
}
